all:
 vars:
  ansible_vault_password_file: vault.yaml
 hosts:
  switch1:
   ansible_host: 192.168.10.10
   ansible_user: switch
   ansible_password: "{{ vault_switch_password }}"
   ansible_connection: network_cli
   ansible_network_os: ios
   ansible_become: yes
   ansible_become_password: "{{ vault_enable_password }}"
   ansible_ssh_common_args: >-
    -oKexAlgorithms=diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
    -oHostKeyAlgorithms=ssh-rsa
    -oCiphers=aes128-ctr,aes192-ctr,aes256-ctr
    -oMACs=hmac-sha1,hmac-sha1-96
   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
   ansible_python_interpreter: /home/myenv/bin/python3
  switch2:
   ansible_host: 192.168.2.10
   ansible_user: switch
   ansible_password: "{{ vault_switch_password }}"
   ansible_connection: network_cli
   ansible_network_os: ios
   ansible_become: yes
   ansible_become_password: "{{ vault_enable_password }}"
   ansible_ssh_common_args: >-
    -oKexAlgorithms=diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
    -oHostKeyAlgorithms=ssh-rsa
    -oCiphers=aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
    -oMACs=hmac-sha1,hmac-sha1-96
   ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
   ansible_python_interpreter: /home/myenv/bin/python3
