---
# File: network_data_collection.yml
# Description: Playbook untuk mengumpulkan dan menganalisis data dari switch jaringan

- name: Collect and analyze data from network switches
  hosts: all
  gather_facts: no
  vars:
    # Direktori utama untuk menyimpan data
    data_directory: "/home/kpc/Network_Monitoring/output"
    # Timestamp untuk direktori unik
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  tasks:
    # 1. Inisialisasi variabel
    - name: Initialize variables
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

    - name: Debug variables
      debug:
        msg:
         - "Data directory: {{ data_directory }}"
         - "Timestamp: {{ timestamp }}"

    # 2. Pastikan direktori induk ada
    - name: Ensure parent directory exists
      file:
        path: "{{ data_directory }}"
        state: directory
        mode: '0755'
      register: parent_dir_creation

    - name: Ensure output dir exists
      file:
       path: /home/kpc/Network_Monitoring/output/{{ timestamp }}
       state: directory
       mode: '0755'

    - name: Debug directory variables
      debug:
        msg:
        - "Parent directory creation: {{ parent_dir_creation }}"
        - "Data directory: {{ data_directory }}"
        - "Timestamp: {{ timestamp }}"

    # 3. Buat direktori dengan timestamp
    - name: Create timestamped directory
      file:
        path: "{{ data_directory }}/{{ timestamp }}"
        state: directory
        mode: '0755'
      register: dir_creation

    - name: Debug dir_creation
      debug:
        var: dir_creation

    - name: add a delay #prevent race condition
      pause:
        seconds: 2

    - name: Debug timestamped directory
      debug:
        msg:
         - "Timestamped directory creation result: {{ dir_creation }}"
         - "Timestamped directory path: {{ data_directory }}/{{ timestamp }}"

    # 4. Periksa apakah direktori berhasil dibuat
    - name: Check if directory exists
      stat:
        path: "{{ data_directory }}/{{ timestamp }}"
      register: dir_check
      retries: 3
      delay: 1
      until: dir_check.stat.exists

    - name: Debug directory existence
      debug:
        var: dir_check.stat.exists

    # 5. Gagal jika direktori tidak dibuat
    - name: Fail if directory creation fails
      fail:
       msg: "Failed to create directory {{ data_directory }}/{{ timestamp }}. Exists: {{ dir_check.stat.exists }}"
      when: not dir_check.stat.exists
      ignore_errors: yes

    # 6. Debug informasi direktori
    - name: Debug directory path
      debug:
        msg: "Data directory is {{ data_directory }}/{{ timestamp }}"

    # 7. Kumpulkan fakta dari switch
    - name: Gather facts from switches
      cisco.ios.ios_facts:
        gather_subset:
          - hardware
          - interfaces
          - default
      register: switch_facts

    - name: Debug collected facts
      debug:
        var: switch_facts.ansible_facts

    # 8. Debug model perangkat
    - name: Debug device model
      debug:
        msg: "Device model is {{ switch_facts.ansible_facts.ansible_net_model }}"

    # 9. Aktifkan SNMP agent
    - name: Enable SNMP agent
      #cisco.ios.ios_snmp_server:
      cisco.ios.ios_config:
       # config:
        #  communities:
         #   - name: "PUBLIC"
          #    ro: true
           #   acl_v4: "90"
        #state: merged
        lines:
          - snmp-server community PUBLIC RO 90

    - name: Debug switch_facts.ansible_facts
      debug:
        var: switch_facts.ansible_facts


    # 10. Dapatkan statistik interface termasuk CRC
    - name: Get interface statistics including CRC
      cisco.ios.ios_command:
        commands:
          - show interfaces | include (up|down|input rate|output rate|input errors|CRC)
          - show ip interface brief
          - show mac address-table
          - show vlan brief
          - show cdp neighbors detail
          - show spanning-tree
          - show version | include (Switch uptime)
          - show processes cpu
          - show processes memory
          - show ip arp
          - show env temperature status
      register: interface_data

    # 11. Debug data interface
    - name: Debug interface data
      debug:
        var: interface_data

    # 12. Ekstrak informasi CRC dari output
    - name: Extract CRC information
      set_fact:
       crc_info: >-
         {% set lines = interface_data.stdout[0].split('\n') %}
         {% set results = [] %}
         {% for line in lines %}
           {% if 'CRC' in line %}
             {% set interface_line = lines[loop.index0 - 1] %}
             {% set interface_name = interface_line.split()[0] %}
             {% set results = results + [interface_name ~ ': '  ~ line.strip()] %}
           {% endif %}
         {% endfor %}
         {{ results | join('\n') }}

    # 13. Debug CRC information
    - name: Debug CRC information
      debug:
        var: crc_info

    - name: Create all-in-one report
      template:
        src: templates/all.j2
        dest: "{{ data_directory }}/{{ timestamp }}/{{ inventory_hostname }}_comprehensive_report.html"
      when: dir_check.stat.exists

